use crate::{crypto::{b64_decode, Identity}, error::{LocalDropError, Result}};
use std::{collections::{HashMap,HashSet}, fs::{self,File}, io::{Read,Seek,SeekFrom,Write}, net::{TcpListener,TcpStream,ToSocketAddrs}, path::PathBuf, sync::{Arc,Mutex}, thread, time::Duration};

pub struct ReceiverHandle { stop: Arc<Mutex<bool>> }
impl Drop for ReceiverHandle { fn drop(&mut self){if let Ok(mut x)=self.stop.lock(){*x=true;}} }
#[derive(Default)] struct State { trusted: HashSet<String> }
pub fn start(identity: Identity, name: String, port: u16) -> Result<(ReceiverHandle,u16)> { let listener=TcpListener::bind(("0.0.0.0",port)).map_err(LocalDropError::Io)?;let actual=listener.local_addr()?.port();listener.set_nonblocking(true)?;let stop=Arc::new(Mutex::new(false));let flag=stop.clone();let state=Arc::new(Mutex::new(State::default()));thread::spawn(move||loop{if *flag.lock().unwrap(){break;}match listener.accept(){Ok((stream,_))=>{let i=identity.clone();let n=name.clone();let s=state.clone();thread::spawn(move||{let _=serve(stream,i,n,s);});},Err(e) if e.kind()==std::io::ErrorKind::WouldBlock=>thread::sleep(Duration::from_millis(30)),Err(_)=>break}});Ok((ReceiverHandle{stop},actual)) }
fn serve(mut stream:TcpStream,identity:Identity,_name:String,state:Arc<Mutex<State>>)->Result<()>{stream.set_read_timeout(Some(Duration::from_secs(120)))?;let(mut path,headers,body)=read_request(&mut stream)?;if path=="/pair-challenge"{let nonce=uuid::Uuid::new_v4().to_string();response(&mut stream,200,"OK",&[("X-LocalDrop-Nonce",nonce.clone()),("X-LocalDrop-Public-Key",identity.public_key.clone()),("X-LocalDrop-Fingerprint",identity.fingerprint.clone()),("X-LocalDrop-Signature",identity.sign(&nonce))],&[]);return Ok(());}if path=="/pair-confirm"{let nonce=h(&headers,"x-localdrop-nonce")?;let pk=h(&headers,"x-localdrop-public-key")?;let fp=h(&headers,"x-localdrop-fingerprint")?;let sig=h(&headers,"x-localdrop-signature")?;let valid=Identity::verify(&pk,&nonce,&sig)&&crate::crypto::fingerprint(&b64_decode(&pk)?)==fp;if !valid{response(&mut stream,401,"Invalid pairing",&[],&[]);return Ok(());}state.lock().unwrap().trusted.insert(pk);response(&mut stream,200,"OK",&[],&[]);return Ok(());}if path=="/upload-chunk"{let pk=h(&headers,"x-localdrop-public-key")?;let sig=h(&headers,"x-localdrop-signature")?;let session=h(&headers,"x-localdrop-session")?;let manifest=String::from_utf8(b64_decode(h(&headers,"x-localdrop-manifest")?)?).map_err(|e|LocalDropError::Manifest(e.to_string()))?;if !state.lock().unwrap().trusted.contains(&pk)||!Identity::verify(&pk,&format!("{session}|{manifest}"),&sig){response(&mut stream,401,"Authentication required",&[],&[]);return Ok(());}let index:hack::usize=h(&headers,"x-localdrop-file-index")?.parse().map_err(|_|LocalDropError::Manifest("índice inválido".into()))?;let offset:u64=h(&headers,"x-localdrop-offset")?.parse().map_err(|_|LocalDropError::Offset("offset inválido".into()))?;let file_size:u64=h(&headers,"x-localdrop-file-size")?.parse().map_err(|_|LocalDropError::Manifest("tamaño inválido".into()))?;let (name,size,sha)=manifest_file(&manifest,index)?;if size!=file_size{return Err(LocalDropError::Manifest("tamaño inconsistente".into()));}let dir=PathBuf::from(std::env::var_os("HOME").unwrap_or_default()).join(".local/share/localdrop-linux-rust/received");fs::create_dir_all(&dir)?;let temp=dir.join(format!("{}.{}.part",session,index));let current=if temp.exists(){fs::metadata(&temp)?.len()}else{0};if offset>current{return Err(LocalDropError::Offset("falta un fragmento anterior".into()));}if offset<current{response(&mut stream,200,"OK",&[("X-LocalDrop-Next-Offset",current.to_string())],&[]);return Ok(());}let mut file=File::options().create(true).write(true).read(true).open(&temp)?;file.seek(SeekFrom::Start(offset))?;file.write_all(&body)?;let next=file.metadata()?.len();if next==size{let actual=sha256_file(&temp)?;if actual!=sha{return Err(LocalDropError::Manifest("SHA-256 no coincide".into()));}let out=unique_path(&dir,&name);fs::rename(&temp,out)?;}response(&mut stream,200,"OK",&[("X-LocalDrop-Next-Offset",next.to_string())],&[]);return Ok(());}response(&mut stream,404,"Not found",&[],&[]);Ok(())}
mod hack {pub type usize=std::primitive::usize;}
fn h(map:&HashMap<String,String>,key:&str)->Result<String>{map.get(key).cloned().ok_or_else(||LocalDropError::Manifest(format!("falta header {key}")))}
fn read_request(stream:&mut TcpStream)->Result<(String,HashMap<String,String>,Vec<u8>)>{let mut head=Vec::new();let mut one=[0u8;1];while !head.ends_with(b"\r\n\r\n"){stream.read_exact(&mut one)?;head.push(one[0]);if head.len()>65536{return Err(LocalDropError::Manifest("headers demasiado grandes".into()));}}let text=String::from_utf8_lossy(&head);let mut lines=text.split("\r\n");let path=lines.next().and_then(|x|x.split_whitespace().nth(1)).unwrap_or("/").to_string();let mut map=HashMap::new();for line in lines{if let Some((k,v))=line.split_once(':'){map.insert(k.to_ascii_lowercase(),v.trim().to_string());}}let len:usize=map.get("content-length").and_then(|x|x.parse().ok()).unwrap_or(0);let mut body=vec![0u8;len];stream.read_exact(&mut body)?;Ok((path,map,body))}
fn response(stream:&mut TcpStream,code:u16,text:&str,headers:&[(&str,String)],body:&[u8]){let mut out=format!("HTTP/1.1 {code} {text}\r\nContent-Length: {}\r\nConnection: close\r\n",body.len());for(k,v)in headers{out.push_str(&format!("{k}: {v}\r\n"));}out.push_str("\r\n");let _=stream.write_all(out.as_bytes());let _=stream.write_all(body);}
fn manifest_file(manifest:&str,index:usize)->Result<(String,u64,String)>{let row=manifest.lines().nth(index).ok_or_else(||LocalDropError::Manifest("índice fuera del manifest".into()))?;let c:Vec<_>=row.split('\t').collect();if c.len()!=4{return Err(LocalDropError::Manifest("fila inválida".into()));}let name=String::from_utf8(b64_decode(c[0])?).map_err(|e|LocalDropError::Manifest(e.to_string()))?;let size=c[1].parse().map_err(|_|LocalDropError::Manifest("tamaño inválido".into()))?;Ok((name,size,c[3].to_string()))}
fn sha256_file(path:&PathBuf)->Result<String>{use sha2::Digest;let mut f=File::open(path)?;let mut d=sha2::Sha256::new();let mut b=[0u8;65536];loop{let n=f.read(&mut b)?;if n==0{break;}d.update(&b[..n]);}Ok(hex::encode(d.finalize()))}
fn unique_path(dir:&PathBuf,name:&str)->PathBuf{let safe=name.replace('/','_');let p=dir.join(&safe);if !p.exists(){return p;}for i in 1..10000{let p=dir.join(format!("{i}-{safe}"));if !p.exists(){return p;}}dir.join(format!("{}-{}",uuid::Uuid::new_v4(),safe))}
pub fn local_ip()->Option<String>{let socket=std::net::UdpSocket::bind("0.0.0.0:0").ok()?;socket.connect("8.8.8.8:80").ok()?;Some(socket.local_addr().ok()?.ip().to_string())}
