cmake_minimum_required(VERSION 3.16)
project(localdrop_linux_cpp LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(CURL REQUIRED)
find_package(OpenSSL REQUIRED)
add_executable(localdrop-linux-cpp main.cpp)
target_link_libraries(localdrop-linux-cpp PRIVATE CURL::libcurl OpenSSL::Crypto)
install(TARGETS localdrop-linux-cpp RUNTIME DESTINATION bin)
