#include <curl/curl.h>
#include <openssl/evp.h>
#include <openssl/pem.h>
#include <openssl/sha.h>
#include <openssl/x509.h>
#include <filesystem>
#include <fstream>
#include <algorithm>
#include <chrono>
#include <sys/stat.h>
#include <iostream>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
#include <iomanip>
#include <random>

namespace fs = std::filesystem;
static const size_t CHUNK = 1024 * 1024;
static std::string b64(const unsigned char* p, size_t n) { int out = 4*((n+2)/3); std::string s(out, '\0'); EVP_EncodeBlock((unsigned char*)s.data(), p, n); while (!s.empty() && s.back()=='=') s.pop_back(); for(char& c:s) { if(c=='+')c='-'; if(c=='/')c='_'; } return s; }
static std::vector<unsigned char> unb64(std::string s) { for(char& c:s){if(c=='-')c='+';if(c=='_')c='/';} while(s.size()%4)s+='='; std::vector<unsigned char> out(3*(s.size()/4)+3); int n=EVP_DecodeBlock(out.data(),(unsigned char*)s.data(),s.size()); if(n<0) throw std::runtime_error("base64 invalido"); while(!s.empty()&&s.back()=='='){s.pop_back();--n;} out.resize(n); return out; }
static std::string hex(const unsigned char* p,size_t n){std::ostringstream o; o<<std::hex<<std::setfill('0');for(size_t i=0;i<n;i++)o<<std::setw(2)<<(int)p[i];return o.str();}
static std::string sha256(const fs::path& path){SHA256_CTX c;SHA256_Init(&c);std::ifstream f(path,std::ios::binary);char b[65536];while(f.read(b,sizeof b)||f.gcount())SHA256_Update(&c,b,f.gcount());unsigned char d[SHA256_DIGEST_LENGTH];SHA256_Final(d,&c);return hex(d,sizeof d);}
static EVP_PKEY* key(){fs::path p=fs::path(getenv("HOME")?getenv("HOME":"."))/".local/share/localdrop-linux-cpp/identity.pem";fs::create_directories(p.parent_path());if(fs::exists(p)){FILE*f=fopen(p.c_str(),"rb");EVP_PKEY*k=PEM_read_PrivateKey(f,nullptr,nullptr,nullptr);fclose(f);if(k)return k;}EVP_PKEY_CTX*c=EVP_PKEY_CTX_new_id(EVP_PKEY_EC,nullptr);EVP_PKEY_keygen_init(c);EVP_PKEY_CTX_set_ec_paramgen_curve_nid(c,NID_X9_62_prime256v1);EVP_PKEY*k=nullptr;EVP_PKEY_keygen(c,&k);EVP_PKEY_CTX_free(c);FILE*f=fopen(p.c_str(),"wb");PEM_write_PrivateKey(f,k,nullptr,nullptr,0,nullptr,nullptr);fclose(f);chmod(p.c_str(),0600);return k;}
static std::string pub(EVP_PKEY*k){unsigned char*b=nullptr;int n=i2d_PUBKEY(k,&b);std::string s=b64(b,n);OPENSSL_free(b);return s;}
static std::string sign(EVP_PKEY*k,const std::string&m){EVP_MD_CTX*c=EVP_MD_CTX_new();EVP_DigestSignInit(c,nullptr,EVP_sha256(),nullptr,k);EVP_DigestSignUpdate(c,m.data(),m.size());size_t n=0;EVP_DigestSignFinal(c,nullptr,&n);std::vector<unsigned char>b(n);EVP_DigestSignFinal(c,b.data(),&n);EVP_MD_CTX_free(c);return b64(b.data(),n);}
static bool verify(const std::string&pk,const std::string&m,const std::string&sig){auto d=unb64(pk);const unsigned char*p=d.data();EVP_PKEY*k=d2i_PUBKEY(nullptr,&p,d.size());auto s=unb64(sig);EVP_MD_CTX*c=EVP_MD_CTX_new();EVP_DigestVerifyInit(c,nullptr,EVP_sha256(),nullptr,k);EVP_DigestVerifyUpdate(c,m.data(),m.size());bool ok=EVP_DigestVerifyFinal(c,s.data(),s.size())==1;EVP_MD_CTX_free(c);EVP_PKEY_free(k);return ok;}
struct Reply{long code{};std::string body;std::map<std::string,std::string> headers;}; static size_t bodycb(char*p,size_t s,size_t n,void*u){((std::string*)u)->append(p,s*n);return s*n;} static size_t headcb(char*p,size_t s,size_t n,void*u){std::string x(p,s*n);auto pos=x.find(':');if(pos!=std::string::npos){std::string k=x.substr(0,pos);for(char&c:k)c=tolower(c);std::string v=x.substr(pos+1);while(!v.empty()&&(v.back()=='\r'||v.back()=='\n'))v.pop_back();while(!v.empty()&&v.front()==' ')v.erase(v.begin());((std::map<std::string,std::string>*)u)->insert_or_assign(k,v);}return s*n;}
static Reply http(const std::string&url,const std::string&method,const std::vector<std::string>&hs,const std::string&data){CURL*c=curl_easy_init();Reply r;curl_easy_setopt(c,CURLOPT_URL,url.c_str());curl_easy_setopt(c,CURLOPT_CUSTOMREQUEST,method.c_str());curl_easy_setopt(c,CURLOPT_POSTFIELDS,data.data());curl_easy_setopt(c,CURLOPT_POSTFIELDSIZE,data.size());curl_easy_setopt(c,CURLOPT_WRITEFUNCTION,bodycb);curl_easy_setopt(c,CURLOPT_WRITEDATA,&r.body);curl_easy_setopt(c,CURLOPT_HEADERFUNCTION,headcb);curl_easy_setopt(c,CURLOPT_HEADERDATA,&r.headers);curl_easy_setopt(c,CURLOPT_TIMEOUT,120L);struct curl_slist*l=nullptr;for(auto&h:hs)l=curl_slist_append(l,h.c_str());curl_easy_setopt(c,CURLOPT_HTTPHEADER,l);auto e=curl_easy_perform(c);if(e!=CURLE_OK)throw std::runtime_error(curl_easy_strerror(e));curl_easy_getinfo(c,CURLINFO_RESPONSE_CODE,&r.code);curl_slist_free_all(l);curl_easy_cleanup(c);return r;}
static std::string qvalue(const std::string&qr,const std::string&key){auto q=qr.find('?');if(q==std::string::npos)return{};std::string x=qr.substr(q+1), needle=key+"=";auto p=x.find(needle);if(p==std::string::npos)return{};p+=needle.size();auto e=x.find('&',p);return x.substr(p,e==std::string::npos?x.size()-p:e-p);}
int main(int argc,char**argv){try{if(argc<3){std::cerr<<"Uso: localdrop-linux-cpp 'localdrop://connect?...' archivo...\n";return 2;}curl_global_init(CURL_GLOBAL_DEFAULT);EVP_PKEY*k=key();std::string pk=pub(k), fp;auto der=unb64(pk);unsigned char dig[SHA256_DIGEST_LENGTH];SHA256(der.data(),der.size(),dig);fp=hex(dig,sizeof dig);std::string host=qvalue(argv[1],"host"),port=qvalue(argv[1],"port"),remote=qvalue(argv[1],"pk"),remoteFp=qvalue(argv[1],"fp");if(host.empty()||port.empty()||remote.empty())throw std::runtime_error("QR incompleto");std::string base="http://"+host+":"+port;auto challenge=http(base+"/pair-challenge","GET",{},"");auto nonce=challenge.headers["x-localdrop-nonce"];if(challenge.code/100!=2||challenge.headers["x-localdrop-fingerprint"]!=remoteFp||!verify(remote,nonce,challenge.headers["x-localdrop-signature"]))throw std::runtime_error("desafio remoto invalido");std::string name="Linux-"+std::string(getenv("USER")?getenv("USER"):"local");auto confirm=http(base+"/pair-confirm","POST",{"X-LocalDrop-Nonce: "+nonce,"X-LocalDrop-Device-Id: "+name,"X-LocalDrop-Device-Name: "+name,"X-LocalDrop-Port: 0","X-LocalDrop-Public-Key: "+pk,"X-LocalDrop-Fingerprint: "+fp,"X-LocalDrop-Signature: "+sign(k,nonce)},"");if(confirm.code/100!=2)throw std::runtime_error("pairing rechazado");std::string session=std::to_string(std::chrono::system_clock::now().time_since_epoch().count());std::string man;std::vector<fs::path> files;for(int i=2;i<argc;i++)files.emplace_back(argv[i]);for(auto&p:files)man+=b64((unsigned char*)p.filename().string().data(),p.filename().string().size())+"\t"+std::to_string(fs::file_size(p))+"\t"+b64((unsigned char*)"application/octet-stream",24)+"\t"+sha256(p)+"\n";std::string sig=sign(k,session+"|"+man);for(size_t i=0;i<files.size();i++){auto&p=files[i];auto size=fs::file_size(p);for(uint64_t off=0;off<size||size==0;){std::ifstream f(p,std::ios::binary);f.seekg(off);std::string chunk(std::min<uint64_t>(CHUNK,size-off),0);f.read(chunk.data(),chunk.size());std::vector<std::string> hs={"Content-Type: application/octet-stream","X-LocalDrop-Session: "+session,"X-LocalDrop-Device-Id: "+name,"X-LocalDrop-Device-Name: "+name,"X-LocalDrop-Public-Key: "+pk,"X-LocalDrop-Fingerprint: "+fp,"X-LocalDrop-Signature: "+sig,"X-LocalDrop-Manifest: "+b64((unsigned char*)man.data(),man.size()),"X-LocalDrop-Chunk: 1","X-LocalDrop-File-Index: "+std::to_string(i),"X-LocalDrop-Offset: "+std::to_string(off),"X-LocalDrop-File-Size: "+std::to_string(size)};auto r=http(base+"/upload-chunk","POST",hs,chunk);if(r.code/100!=2)throw std::runtime_error("fragmento rechazado");auto it=r.headers.find("x-localdrop-next-offset");uint64_t next=it==r.headers.end()?off+chunk.size():std::stoull(it->second);if(next<=off||next>size)throw std::runtime_error("offset invalido");off=next;if(size==0)break;}std::cout<<"Enviado: "<<p<<"\n";}EVP_PKEY_free(k);curl_global_cleanup();return 0;}catch(const std::exception&e){std::cerr<<"Error: "<<e.what()<<"\n";return 1;}}
